spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/e_learning
    username: username
    password: password
    driver-class-name: org.postgresql.Driver # optional --> can be automatically detected by Spring
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: spring-boot-rest-demo
server:
  servlet:
    context-path: /api/v1

application:
  security:
    jwt:
      secret-key: 210D3D27605D0EE737952294265400A7CBA109746AFACD84B9CB0139BF6B7E3A
      expiration: 86400000

#logging:
#  level:
#    org.springframework: debug
