spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/e_learning
    username: username
    password: password
    driver-class-name: org.postgresql.Driver # optional --> can be automatically detected by Spring
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: spring-boot-rest-demo
server:
  servlet:
    context-path: /api/v1
