spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/e_learning
    username: username
    password: password
    driver-class-name: org.postgresql.Driver # optional --> can be automatically detected by Spring
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: spring-boot-rest-demo

#server:
#  servlet:
#    context-path: /api/v1

classroom:
  openapi:
    base-url: http://localhost:8080

token:
  secret:
    key: 48a868a4042f634ac04a117f00a87202131dd7c46c4b32c4acb3edc5e15f4511
  expirationms: 223600000

logging:
  level:
    org.springframework.boot.web: DEBUG
    org.apache.catalina.core: DEBUG

springdoc:
  swagger-ui:
    filter: true
    tagsSorter: alpha
    enabled: true
    operationsSorter: method
    path: /api/docs/index.html
  api-docs:
    path: /v3/api-docs
  use-yaml: true
